### ISSUE TITLE
请问支持自动化配置爬虫嘛

### ISSUE THREAD

**Issue by carl-don-it** [zhaoyachao/zdh_web#10]
数据先要爬取，数据源选择可以快速构建爬虫吗

**Comment by zhaoyachao** [comment]
不支持爬虫数据源,爬虫数据-需要用户自己实现爬虫采集逻辑，可通过zdh提供的SSH任务进行执行和调度




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaoyachao/zdh_web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 中午11:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaoyachao/zdh_web] 请问支持自动化配置爬虫嘛 (#10)





 
数据先要爬取，数据源选择可以快速构建爬虫吗

**Comment by carl-don-it** [comment]
好的
