### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by rogerlee24** [zhaoyachao/zdh_web#15]
你好，从您的仓库下载了4.7.16-RELEASE版本的zdh_web代码，在修改完配置文件后，在cmd窗口执行java -jar -Dfile.encoding=utf-8 -Dloader.path=libs/,conf zdh_web.jar 后启动错误，报错如下
![image](https://user-images.githubusercontent.com/57137841/147576095-983b13b5-bd5b-40a1-9f66-a2c3185dced6.png)
可以帮忙看一下吗？非常感谢~

**Comment by rogerlee24** [comment]
@zhaoyachao

**Comment by zhaoyachao** [comment]
你好，请确认你的application相关配置文件中是否包含org…threadcount参数，在window上执行此命令，请确认在zdh_web.jar的同级目录下执行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 运行出错 (Issue #15)





 
@zhaoyachao
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogerlee24** [comment]
@zhaoyachao  配置文件中没有thraedcount参数，下载后只在application-dev中改了数据库信息，而且是在zdh_web.jar同级目录执行的java -jar -Dfile.encoding=utf-8 -Dloader.path=libs/,conf zdh_web.jar，即4.7.16-RELEASE目录下

另外上面还有其他报错信息
![image](https://user-images.githubusercontent.com/57137841/147738834-026d8b63-46e6-4557-8398-c6e851745f72.png)

我不确定这是不是根本原因

**Comment by zhaoyachao** [comment]
在配置文件中增加org.quartz.threadPool.threadCount=5参数，上方错误，属于历史jar版本变动引起，不影响




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 下午5:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 运行出错 (Issue #15)





 
@zhaoyachao  配置文件中没有thraedcount参数，下载后只在application-dev中改了数据库信息，而且是在zdh_web.jar同级目录执行的java -jar -Dfile.encoding=utf-8 -Dloader.path=libs/,conf zdh_web.jar，即4.7.16-RELEASE目录下
 
另外上面还有其他报错信息
 
 
我不确定这是不是根本原因
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogerlee24** [comment]
@zhaoyachao 在配置文件中增加org.quartz.threadPool.threadCount=5之后，消除了原先的bug
但是遇到了新的问题，sql语句出错  错误详情如下
![image](https://user-images.githubusercontent.com/57137841/147804499-9f475d0a-a269-48b8-a3a3-05bca4afed5d.png)
![image](https://user-images.githubusercontent.com/57137841/147804511-dfafbced-1d01-4f32-8e2b-2d574bdcbaa0.png)

![image](https://user-images.githubusercontent.com/57137841/147804536-90085fa1-d937-41b4-8d76-4837978c9dca.png)
这个语句应该没有错误的。
可以帮忙看一下吗？谢谢

**Comment by zhaoyachao** [comment]
源码目前只开源4.7.10， 使用4.7.10版本，请勿使用其他版本的配置及编译包，请检查配置文件信息是否对应




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 中午1:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 运行出错 (Issue #15)





 
@zhaoyachao 在配置文件中增加org.quartz.threadPool.threadCount=5之后，消除了原先的bug
 但是遇到了新的问题，sql语句出错  错误详情如下
 
 
 

 这个语句应该没有错误的。
 可以帮忙看一下吗？谢谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogerlee24** [comment]
@zhaoyachao  用4.7.10版本时访问页面时出现以下错误
![image](https://user-images.githubusercontent.com/57137841/147805710-b2c7f5da-f0e6-4566-860b-bd7016871254.png)
![image](https://user-images.githubusercontent.com/57137841/147805742-17ff6891-2101-4466-8bd8-b90557560d7f.png)

页面如下，显示不完全
![image](https://user-images.githubusercontent.com/57137841/147805723-72e95cce-295b-4e74-96b5-c8e79d3209bc.png)

**Comment by zhaoyachao** [comment]
every_day_notice接口,可加为空判断，4.7.10版本建议自行修复，也可在every_day_notice增加通知信息，该bug将于4.7.17版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 中午1:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 运行出错 (Issue #15)





 
@zhaoyachao  用4.7.10版本时访问页面时出现以下错误
 
 
 
页面如下，显示不完全
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogerlee24** [comment]
@zhaoyachao 好的谢谢

**Comment by rogerlee24** [comment]
@zhaoyachao 你好，在every_day_notice接口加上空判断后正常运行，但首页左侧好像显示不完全，如下图，可以帮忙看一下吗谢谢
![image](https://user-images.githubusercontent.com/57137841/147867994-f2f15453-bdbb-47d0-bb02-9c0254c910cd.png)
与演示不同
![image](https://user-images.githubusercontent.com/57137841/147868060-3a050482-77c0-4a87-acab-595a6e2a3f64.png)

**Comment by rogerlee24** [comment]
@zhaoyachao 你好，可以帮看一下吗？

**Comment by zhaoyachao** [comment]
请严格按照版本对应的sql文件进行导入，4.7.10之后每个版本变更都很大，不通用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月5日(星期三) 晚上6:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 运行出错 (Issue #15)





 
@zhaoyachao 你好，可以帮看一下吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
