### ISSUE TITLE
我只启动了web项目注册了用户但是没有菜单

### ISSUE THREAD

**Issue by zhsngq** [zhaoyachao/zdh_web#23]
我初始化的sql是resources/db.sql。
项目是直接download当前源码zip，我不知道当前download下来的是哪个版本!!!

**Comment by zhaoyachao** [comment]
你好源码开放至4.7.10，可通过github上branch-v4.7.10下载，免费安装包请通过readme文档提供的下载路径下载，或者通过预览页面中 下载指定版本安装包，注册用户看不到菜单，请通过提供的管理用户zyc，登录并赋予注册用户权限




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月18日(星期五) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zhaoyachao/zdh_web] 我只启动了web项目注册了用户但是没有菜单 (Issue #23)





 
我初始化的sql是resources/db.sql。
 项目是直接download当前源码zip，我不知道当前download下来的是哪个版本!!!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by javenyuan** [comment]
作者你好，看到这个项目挺不错的，我拉取的是branch-v4.7.10 版本的代码，按照readme 进行操作，初始化数据库，只启动了  zdh_web 工程，可以登录，进去后只有首页，看不到其他菜单，检查了一下db.sql 发现sql 里面只有account_info 表 ，没有和 权限 和菜单相关的其他表

**Comment by zhaoyachao** [comment]
你好，在release/db 目录下有表数据sql，可从中拉取权限信息数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 我只启动了web项目注册了用户但是没有菜单 (Issue #23)





 
作者你好，看到这个项目挺不错的，我拉取的是branch-v4.7.10 版本的代码，按照readme 进行操作，初始化数据库，只启动了  zdh_web 工程，可以登录，进去后只有首页，看不到其他菜单，检查了一下db.sql 发现sql 里面只有account_info 表 ，没有和 权限 和菜单相关的其他表
