### ISSUE TITLE
使用greenplum数据库，在建立ETL时无法列出tables

### ISSUE THREAD

**Issue by psx516** [zhaoyachao/zdh_web#27]
使用的是5.0的服务端和web端，greenplum的驱动采用的压缩包里的。
采用greenplum驱动和postgresql驱动都尝试了，依然无法获取tables列表
数据源那里的测试都可以通过，没问题
jdbc:pivotal:greenplum://*.*.*.*:5432;databaseName=
jdbc:postgresql://*.*.*.*:5432/postgres

**Comment by zhaoyachao** [comment]
已确认属于bug,在5.0.1版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月27日(星期一) 中午11:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zhaoyachao/zdh_web] 使用greenplum数据库，在建立ETL时无法列出tables (Issue #27)





 
使用的是5.0的服务端和web端，greenplum的驱动采用的压缩包里的。
 采用greenplum驱动和postgresql驱动都尝试了，依然无法获取tables列表
 数据源那里的测试都可以通过，没问题
