### ISSUE TITLE
5.1.1版本，zdh_web启动，QRTZ_SCHEDULER_STATE中没有数据

### ISSUE THREAD

**Issue by anyangdp** [zhaoyachao/zdh_web#36]
本地服务我创建了个etl任务，执行一直是失败，后续我查看发现，没有调度器
<img width="1674" alt="image" src="https://github.com/zhaoyachao/zdh_web/assets/22770337/6c9ee4fd-d579-4386-831b-ca943645894c">
，我看到你演示环境是有的
<img width="1453" alt="image" src="https://github.com/zhaoyachao/zdh_web/assets/22770337/6dfe1e6f-a2d0-45fe-a42a-b0ef509917c8">
这是什么原因，不是启动时候自动添加调度器到QRTZ_SCHEDULER_STATE表中的么？

**Comment by anyangdp** [comment]
<img width="1456" alt="image" src="https://github.com/zhaoyachao/zdh_web/assets/22770337/fb0f994a-f77c-4d54-9b4e-8422df4d4179">
我创建了个etl的任务，里面只有个查询sql，定时10s，没有执行这个定时任务，也没有相关错误日志。

**Comment by anyangdp** [comment]
<img width="900" alt="image" src="https://github.com/zhaoyachao/zdh_web/assets/22770337/d54de93f-2ee4-42ce-a551-a6520aef416b">
我看了执行调度的代码那里，我看到你把调度自启动关闭了，然后这里也不让它启动，是不是你是测试环境所以关闭了，我们如果真实想测试的话，是不是要放开注释？

**Comment by zhaoyachao** [comment]
可看下application.properties 配置文件，包含启动调度器 配置，可以看下配置是否是关闭的&nbsp;


18岁的年华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月8日(星期天) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 5.1.1版本，zdh_web启动，QRTZ_SCHEDULER_STATE中没有数据 (Issue #36)





  我看了执行调度的代码那里，我看到你把调度自启动关闭了，然后这里也不让它启动，是不是你是测试环境所以关闭了，我们如果真实想测试的话，是不是要放开注释？

**Comment by anyangdp** [comment]
配置文件中没有写类似关闭的配置，我将您代码中的注释放开后，现在定时任务已经正常能够启动了，但是现在遇到了新的问题，调度执行的etl任务是失败的，它一直没有执行完成。

**Comment by anyangdp** [comment]
<img width="1648" alt="image" src="https://github.com/zhaoyachao/zdh_web/assets/22770337/c17535da-f5fc-40d1-8bc7-14ef4b83ba2d">
我写了个测试的etl任务，里面主要内容就是将一张mysql表中的数据，复制指定日期到另外一张表中。

**Comment by zhaoyachao** [comment]
可点击子任务查看相关原因,功能相关问题可自行摸索
&nbsp;


18岁的年华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月8日(星期天) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 5.1.1版本，zdh_web启动，QRTZ_SCHEDULER_STATE中没有数据 (Issue #36)





  我写了个测试的etl任务，里面主要内容就是将一张mysql表中的数据，复制指定日期到另外一张表中。

**Comment by zhaoyachao** [comment]
调度系统运行启动是通过配置文件控制的,此处打开后将无法通过web端控制调度,可以查看下调度系统是否正常启动,目前调度系统应该是随服务启动运行，如果启动系统后未运行调度，1可检查配置文件是否有开启自动启动配置，2检查quartz数据库配置,3从release/db目录下查看quartz 相关表结构，基于quartz二次开发的调度，修改了部分表结构
&nbsp;


18岁的年华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月8日(星期天) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoyachao/zdh_web] 5.1.1版本，zdh_web启动，QRTZ_SCHEDULER_STATE中没有数据 (Issue #36)





 
配置文件中没有写类似关闭的配置，我将您代码中的注释放开后，现在定时任务已经正常能够启动了，但是现在遇到了新的问题，调度执行的etl任务是失败的，它一直没有执行完成。

**Comment by anyangdp** [comment]
好的，感谢感谢，我在application.prod环境下看到了定时任务的相关配置。定时任务调度已经解决，其他问题，我再仔细研究研究。感谢了！！！
