### ISSUE TITLE
增量抽取binlog抽取支持吗

### ISSUE THREAD

**Issue by juice411** [zhaoyachao/zdh_web#6]
增量抽取binlog抽取支持吗

**Comment by zhaoyachao** [comment]
当前版本是不支持的，以后的版本会加入的，如果特别需要，建议自行修改server的源码

**Comment by juice411** [comment]
我们想完善下这个系统，可以出人力，包括前后端，希望在你的带领下能一起做，可以的话列个计划？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaoyachao/zdh_web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午12:41
收件人:&nbsp;"zhaoyachao/zdh_web"<zdh_web@noreply.github.com&gt;;
抄送:&nbsp;"张景"<66953872@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhaoyachao/zdh_web] 增量抽取binlog抽取支持吗 (#6)





 
当前版本是不支持的，以后的版本会加入的，如果特别需要，建议自行修改server的源码

**Comment by zhaoyachao** [comment]
你好
&nbsp;&nbsp;  非常高兴收到同学你的来信,也非常感谢你们对此项目的关注，因个人工作和家庭原因,个人时间不会特别宽裕,如果同学想完善这个系统，我非常乐意提供一些帮助。此项目也是一种对大数据可视化方向的一个探索,不会有明确的计划,开源代表了无限可能，不管你是在此基础上做修改，还是因为此项目产生新的灵感找到新的方向,都可以提到issue,我会尽最大的努力和大家一起为zdh添砖加瓦
&nbsp;&nbsp;&nbsp; 感谢同学对zdh的做出的贡献



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaoyachao/zdh_web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 中午11:38
收件人:&nbsp;"zhaoyachao/zdh_web"<zdh_web@noreply.github.com&gt;;
抄送:&nbsp;"18岁的年华"<1209687056@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhaoyachao/zdh_web] 增量抽取binlog抽取支持吗 (#6)





 我们想完善下这个系统，可以出人力，包括前后端，希望在你的带领下能一起做，可以的话列个计划？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zhaoyachao/zdh_web"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年8月12日(星期三) 中午12:41 
 收件人:&amp;nbsp;"zhaoyachao/zdh_web"<zdh_web@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"张景"<66953872@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [zhaoyachao/zdh_web] 增量抽取binlog抽取支持吗 (#6) 
 
 
 
 
 
   
 当前版本是不支持的，以后的版本会加入的，如果特别需要，建议自行修改server的源码

**Comment by wuyascnu** [comment]
能集成flink进来吗

**Comment by zhaoyachao** [comment]
会集成flink，初版只支持flink-sql ddl模式，最早集成会在2021年7月实现------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月25日(星期二) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaoyachao/zdh_web] 增量抽取binlog抽取支持吗 (#6)

**Comment by zhaoyachao** [comment]
4. 7. 11版本以集成flink
